# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Andrew Murray"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://amurraygeo.com/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "125661405"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "hugo-academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

## Weights for geog information course menu
[[menu.geog_info]]
  name = "Course Overview"
  weight = 1
  url = "/courses/geog_info/"
  
[[menu.geog_info]]
  name = "Week 1"
  weight = 10
  identifier = "week1"

## Weights for watershed course menu
[[menu.watershed]]
  name = "Course Overview"
  weight = 5
  url = "/courses/watershed/"

[[menu.watershed]]
  name = "Lectures"
  weight = 10
  identifier = "lectures"
  
[[menu.watershed]]
  name = "Fridays (R)"
  weight = 20
  identifier = "fridays"

[[menu.watershed]]
  name = "Exams / Project"
  weight = 30
  identifier = "exams"

[[menu.watershed]]
  name = "Resources"
  weight = 40
  identifier = "resources"

## Weights for Tropical Cyclone Project
[[menu.cyclones]]
  name = "Overview"
  weight = 5
  url = "/projects/cyclones/"

[[menu.cyclones]]
  name = "Tropical Cyclones"
  weight = 10
  identifier = "cyclones"
  
[[menu.cyclones]]
  name = "Drivers of Connectivity"
  weight = 20
  identifier = "drivers"  