---
title: "Watershed Hydrology: Lecture 1"
author: Andrew Murray
date: 
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(imager)

```


## What is Hydrology?

  Water (quite literally) shapes the planet. It is something that relates to almost everything important in our lives. The study of hydrology is a broad one and encompasses everything relating to the physical movement of water and the effects that water movement has on both the natural and built environments.

## Hornberger says:

> *"Hydrological science has aspects related to "curiosity-driven" questions and to "problem-driven" questions. The first aspect relates to questions about how the Earth works, and specifically about the role of water in natural processes. The second relates to using scientific knowledge to provide a sound basis for the proper use and protection of water resources"*

**Curiosity-driven:** How was the Grand Canyon formed?

**Problem-driven:** Where is all of this nitrogen coming from that's in our drinking water?



