---
title: "Lecture 3"
author: "Andrew"
date: "Wednesday, January 15, 2020"
output:
  ioslides_presentation:
    widescreen: true
    smaller: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Outline
- The water balance equation
- Residence time
- Runoff ratio
- Observations
- The watershed as the fundamental unit

## {data-background=/img/watershed/lecture3/WB1.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/WB2.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/WB3.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/WB4.png data-background-size=cover}

## Residence Time

$Tr = \frac{V}{I}$

"Residence time has dimensions of time because volume divided by volume per time is time"

- [T] is time...
  - r refers to the 'residence'
- [V] is volume
- I is inflow

Remember this is at steady state where inflow and outflow rates are identical.

So what are the units...?

## {data-background=/img/watershed/lecture3/residence.png data-background-size=cover}

## Runoff Ratio

### The proportion of precipitation that becomes runoff

$R_r = \frac{\overline{r_s}}{\overline{p}}$

AKA - How mch rain does not get absorbed by the ground, plants etc...

## {data-background=/img/watershed/lecture3/Slide1.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide2.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide3.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide4.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide5.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide6.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide7.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide8.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide9.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide10.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide11.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide12.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide13.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide14.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide15.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide16.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide17.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide18.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide19.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide20.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide21.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide22.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide23.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide24.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide25.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide26.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide27.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide28.png data-background-size=cover}
## {data-background=/img/watershed/lecture3/Slide29.png data-background-size=cover}

