---
date: "2020-06-21T12:05:00-05:00"
draft: false
output:
  blogdown::html_page:
    toc: true
linktitle: Geog 370
summary: Introduction to Geographic Information
title: "Course Overview"
type: docs
---

# Welcome to Geography 370!

[Click here to get started!](https://murraygeo.com/slides/intro_geographic_information/Day01/slides.html)

## A few quick points:

- This course will be asynchronous, which means that you will be responsible for viewing the lectures and completing the work on your own schedule.

- I will be available to talk with you one-on-one as needed throughout the course to help with issues along the way (and I am sure there will be many!) with weekly (virtual) office hours and by appointment.

- We are using advanced software for this class and we will need to navigate how to manage this as some of you will not have access to the software, or possibly a stable internet connection. I will do my best to help you navigate these obstacles.

## What to expect

This course will be a mix of reading, discussion and computer work. I'm going to introduce you to basic geographic concepts and we're going to quickly move into working with geographic information systems to reinforce these concepts. This course really is somewhat of a guinea pig for the fall semester geography courses so I anticipate we will run into some issues with computers and software. Thus, it is extremely important that in these first few days of class, you work to identify potential problems. I will be providing an exercise to work through as a way to check for potential issues so that we can try to catch as many of them as early as possible.

We will be using **Piazza** to help facilitate class discussion and as a platform to ask questions that others may also have. [Click here](https://piazza.com/class/kbchpg3on0h4se?cid=3#) to go to our course page.

## Materials

We will be reading [Essentials of Geographic Information Systems](https://open.umn.edu/opentextbooks/textbooks/essentials-of-geographic-information-systems), which is a free and open source textbook.

## Calendar

| Date          | Topic               | Description | Reading | Assignment  |
| ------------- | ------------------- | ----------- | ------------- | ----- |
| June 22, 2020 | [Course Introduction](https://murraygeo.com/slides/intro_geographic_information/Day01/slides.html) |  | | [Read Chapter 1](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s05-introduction.html) / [Post your introduction](https://piazza.com/class/kbchpg3on0h4se?cid=7) |
| June 23, 2020 | [Spatial thinking and concepts](https://murraygeo.com/slides/intro_geographic_information/Day02/slides.html)| | [Chapter 1](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s05-introduction.html)| |
| June 24, 2020 | [GIS & Intro to ArcGIS](https://murraygeo.com/slides/intro_geographic_information/Day03/slides.html) | Finish Chapter 1 & Introduce GIS software |  | Assign Lab 1|
| June 25, 2020 | [Maps and Projections](https://murraygeo.com/slides/intro_geographic_information/Day04/slides.html)  | Introduce Maps, coordinate systems and Projections | [Chapter 2](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s06-map-anatomy.html) ||
| June 26, 2020 | [Map Abstractions](https://murraygeo.com/slides/intro_geographic_information/Day01/slides.html)    | Finish Chapter 2 | [Chapter 2](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s06-map-anatomy.html) | Lab 1 Due + Quiz 1 |
| June 29, 2020 | [Data & Where to find them](https://murraygeo.com/slides/intro_geographic_information/Day06/slides.html) | All about data | [Chapter 3](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s07-data-information-and-where-to-.html) | Assign Lab 2|
| June 30, 2020 | Data Models for GIS |             | [Chapter 4](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s08-data-models-for-gis.html)              ||
| July 1, 2020  | Data Models for GIS |             | [Chapter 4](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s08-data-models-for-gis.html)| Lab 2 due + Assign Lab 3|
| July 2, 2020  | Geospatial Data Management | What to do with data | [Chapter 5](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s09-geospatial-data-management.html) | Quiz 2 (will not include chapter 5)|
| July 3, 2020  | HOLIDAY             | NO          | CLASS         ||
| July 6, 2020  | Geospatial Data Management | Chapter 5 | [Chapter 5](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s09-geospatial-data-management.html) | Lab 3 due |
| July 7, 2020  | Finish Chapter 5 + Data Characteristics & Visualization |             | [Chapter 6](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s10-data-characteristics-and-visua.html) | Assign Lab 4 |
| July 8, 2020  | Data Characteristics & Visualization | Finish Chapter 6 | [Chapter 6](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s10-data-characteristics-and-visua.html)  ||
| July 9, 2020  | Vector Operations   |             | [Chapter 7](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s11-geospatial-analysis-i-vector-o.html) | Lab 4 due + Assign Lab 5|
| July 10, 2020 | Vector Operations cont'd| Finish Chapter 7| [Chapter 7](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s11-geospatial-analysis-i-vector-o.html) | Quiz 3  |
| July 13, 2020 | Raster Data |  |  [Chapter 8](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s12-geospatial-analysis-ii-raster-.html)  ||
| July 14, 2020 |  Raster Data cont'd |             | [Chapter 8](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s12-geospatial-analysis-ii-raster-.html) | Lab 5 due + Assign Lab 6|
| July 15, 2020 | Final Project Overview |  Introduce final project |               | Assign Final Project|
| July 16, 2020 | Cartographic Principles|             | [Chapter 9](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s13-cartographic-principles.html) | Lab 6 due|
| July 17, 2020 | Cartographic Principles cont'd |             | [Chapter 9](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s13-cartographic-principles.html)  | Quiz 4 |
| July 20, 2020 | GIS Project Management |             | [Chapter 10](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s14-gis-project-management.html) | **Final Project Proposal Due**|
| July 21, 2020 | Individual Meetings | I will meet individually to discuss your final project | ||
| July 22, 2020 | Advanced Topics in ArcGIS |             |               ||
| July 23, 2020 | Advanced Topics in ArcGIS |             |               ||
| July 24, 2020 | Reading Day         |             |               ||
| July 27, 2020 | **Final Project Due** |             |               |**Final Project Due**|



