---
date: "2020-01-26T00:00:00+01:00"
draft: false
output:
  blogdown::html_page:
    toc: false
linktitle: Exam 1
menu:
  watershed:
    parent: Exams / Project
    weight: 110
title: Exam 1
type: docs

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Main Points

- Monday, February 10
- 50 minute Exam
- Bring a calculator
- I will provide exam, no need for scantron or blue book

## Format

- Short Answer
- Fill in the blank
- Calculations
- Fill in the graph

## What to study

- Read Chapter 1-2 & Appendix 1 & 3
- Study the **Key Terms**
- Study the slides with particular attention to formulas and graphs/plots/figures

## Equations:

- Water Balance Equation (Lecture 3)
- Residence Time (Lecture 3)
- Runoff Ratio (Lecture 3)
- Exceedance probability (Lecture 6)

## Watersheds

### Be able to:
- Define a watershed
- Explain the water cycle in the context of a watershed
- Explain the difference between surface and groundwater

## Scale
You need to be able to talk about the effects of scale in hydrology. Make sure to understand the differences in process scale and observtion scale. Be able to effectively communicate the differences in areal precipitation estimation methods.

## Units
You should be familiar with the following basic unit conversions:

Hectares [ha] to $m^2$ to [mm]

You should be familiar with the concept of Dimensional Analysis (Lecture 4)

- Units vs. Dimensions