---
title: "Friday (1)"
date: "2020-01-09T00:00:00+01:00"
draft: false
output:
  blogdown::html_page:
    toc: true
linktitle: Friday (1)
menu:
  watershed:
    parent: The Science of Hydrology
    weight: 1
    type: docs
weight: 40
---

[Slides are here!](https://amurraygeo.com/slides/watershed/RDay_1.html)

## Getting Started with R and R studio
R is a programming language that we install on our computer, whereas R studio is the program we will use to interact with the language. R studio is great because it has a large number of things that save time and help us code with as little memorization as possible. For example, it has all of the documentation and help files for every function in R built in. If you start to type the name of a file or the name of a function, r studio will auto-complete it (which saves a huge amount of time). If you are unfamiliar with what a 'function', think of it as a tool that has a specific purpose. For example, in microsoft excel, when you want to add up the numbers from a bunch of different cells you would click in an empty cell and type '=SUM(A2:A10)' or something like that. In this case 'SUM' is the function that excel is using. R is built on functions and some are really simple (like SUM) and some are realllllly complicated, but the beauty is that once someone else has written the function, we don't really have to mess with it, we can just use it the same way we would use any other tool. A good way to think about this is buying a power saw at a hardware store (or insert other complex machine). I can use a a power saw to cut wood, but I'm certainly not going to build a power saw from parts to do it. I'm going to buy a power saw that someone else built. 

Go to the slides above to get started.
