---
title: "Day 1"
author: "Andrew Murray"
date: 'June 22, 2020'
output:
  xaringan::moon_reader:
    css: ["default"]
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      highlightStyle: github
      countIncrementalSlides: false
    seal: false
    includes:
      after_body: "afterInit.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

.center[

## Introduction to Geographic Information

### Geography - 370

<br><br>

.mb[**Welcome to the class!**]

<br><br><br>

Andrew Murray | University of North Carolina - Chapel Hill

March 25, 2020
]

---
.pull-left[
<video width="100%" height="100%" controls id="my_video">
    <source src="/mp4/Day_01_intro.mp4" type="video/mp4" preload>
</video>

Andrew Murray
PhD Candidate (Geography)
]

.pull-right[
## Welcome to Geography 370

Move through the slides at your own pace and I will provide commentary along the way.

- These slides are in a format called 'xaringan' and use the following [keyboard shortcuts](https://bookdown.org/yihui/rmarkdown/xaringan-key.html):

- Press 'f' to toggle fullscreen

- type a number + 'enter' to go to that slide

- press 'home' to return to the first slide

- press 'p' to access the text for the slide audio (useful for those who cannot use audio or need a an audio aid)

]
---

### Todays Roadmap

- Course Content & Goals
- Course Syllabus
- Software Introduction

<audio controls>
  <source src="/slides/intro_geographic_information/Day01/audio/slide_02.mp4" type="audio/mpeg">
  <track kind="captions" label="English SubTitles" src="/slides/intro_geographic_information/Day01/audio/slide02.srt" srclang="en" />
</audio>

???
Today we are simply going to talk about what you can expect to learn throughout this course and how we are going to learn it. I'm going to introduce some basic concepts to you and we will talk about the syllabus, and the materials (both reading and software).

---
